import streamlit as st
from PIL import Image # 위에서 선언 후 사용해야한다.

st.title("Word Cloud using GAO reports")

tabs = st.tabs(["GAO_EN", "GAO_한글"])

with tabs[0]:
  # 경로에 있는 이미지 파일을 통해 변수 저장
  img1 = Image.open('images/en/Agriculture and Food.png')
  img2 = Image.open('images/en/Auditing and Financial Management.png')
  img3 = Image.open('images/en/Budget and Spending.png')
  img4 = Image.open('images/en/Business Regulation and Consumer Protection.png')
  img5 = Image.open('images/en/Economic Development.png')
  img6 = Image.open('images/en/Education.png')
  img7 = Image.open('images/en/Employment.png')
  img8 = Image.open('images/en/Energy.png')
  img9 = Image.open('images/en/Equal Opportunity.png')
  img10 = Image.open('images/en/Financial Markets and Institutions.png')
  img11 = Image.open('images/en/GAO Mission and Operations.png')
  img12 = Image.open('images/en/Government Operations.png')
  img13 = Image.open('images/en/Health Care.png')
  img14 = Image.open('images/en/Homeland Security.png')
  img15 = Image.open('images/en/Housing.png')
  img16 = Image.open('images/en/Human Capital.png')
  img17 = Image.open('images/en/Information Management.png')
  img18 = Image.open('images/en/Information Security.png')
  img19 = Image.open('images/en/Information Technology.png')
  img20 = Image.open('images/en/International Affairs.png')
  img21 = Image.open('images/en/Justice and Law Enforcement.png')
  img22 = Image.open('images/en/National Defense.png')
  img23 = Image.open('images/en/Natural Resources and Environment.png')
  img24 = Image.open('images/en/Retirement Security.png')
  img25 = Image.open('images/en/Science and Technology.png')
  img26 = Image.open('images/en/Space.png')
  img27 = Image.open('images/en/Tax Policy and Administration.png')
  img28 = Image.open('images/en/Telecommunications.png')
  img29 = Image.open('images/en/Transportation.png')
  img30 = Image.open('images/en/Veterans.png')
  img31 = Image.open('images/en/Worker and Family Assistance.png')
  img32 = Image.open('images/en/nan.png')
  
    
  # streamlit를 통해 이미지를 보여준다.
  st.image(img1)
  st.divider()
  st.image(img2)
  st.divider()
  st.image(img3)
  st.divider()
  st.image(img4)
  st.divider()
  st.image(img5)
  st.divider()
  st.image(img6)
  st.divider()
  st.image(img7)
  st.divider()
  st.image(img8)
  st.divider()
  st.image(img9)
  st.divider()
  st.image(img10)
  st.divider()
  st.image(img11)
  st.divider()
  st.image(img12)
  st.divider()
  st.image(img13)
  st.divider()
  st.image(img14)
  st.divider()
  st.image(img15)
  st.divider()
  st.image(img16)
  st.divider()
  st.image(img17)
  st.divider()
  st.image(img18)
  st.divider()
  st.image(img19)
  st.divider()
  st.image(img20)
  st.divider()
  st.image(img21)
  st.divider()
  st.image(img22)
  st.divider()
  st.image(img23)
  st.divider()
  st.image(img24)
  st.divider()
  st.image(img25)
  st.divider()
  st.image(img26)
  st.divider()
  st.image(img27)
  st.divider()
  st.image(img28)
  st.divider()
  st.image(img29)
  st.divider()
  st.image(img30)
  st.divider()
  st.image(img31)
  st.divider()
  st.image(img32)
  st.divider()
  st.write("by gKim")

with tabs[1]:  
  image1 = Image.open('images/ko/GAO 임무 및 운영.png')
  image2 = Image.open('images/ko/감사 및 재무 관리.png')
  image3 = Image.open('images/ko/건강 관리.png')
  image4 = Image.open('images/ko/경제 발전.png')
  image5 = Image.open('images/ko/고용.png')
  image6 = Image.open('images/ko/공간.png')
  image7 = Image.open('images/ko/과학기술.png')
  image8 = Image.open('images/ko/교육.png')
  image9 = Image.open('images/ko/국방.png')
  image10 = Image.open('images/ko/국제교류.png')
  image11 = Image.open('images/ko/국토안보부.png')
  image12 = Image.open('images/ko/근로자 및 가족 지원.png')
  image13 = Image.open('images/ko/금융 시장 및 기관.png')
  image14 = Image.open('images/ko/기회균등.png')
  image15 = Image.open('images/ko/농업 및 식품.png')
  image16 = Image.open('images/ko/세금 정책 및 행정.png')
  image17 = Image.open('images/ko/업무 규제 및 소비자 보호.png')
  image18 = Image.open('images/ko/에너지.png')
  image19 = Image.open('images/ko/예산 및 지출.png')
  image20 = Image.open('images/ko/운송.png')
  image21 = Image.open('images/ko/인적 자본.png')
  image22 = Image.open('images/ko/재향군인.png')
  image23 = Image.open('images/ko/정보 기술.png')
  image24 = Image.open('images/ko/정보 보안.png')
  image25 = Image.open('images/ko/정보관리.png')
  image26 = Image.open('images/ko/정부 운영.png')
  image27 = Image.open('images/ko/정의와 법 집행.png')
  image28 = Image.open('images/ko/주택.png')
  image29 = Image.open('images/ko/천연자원과 환경.png')
  image30 = Image.open('images/ko/통신.png')
  image31 = Image.open('images/ko/퇴직연금.png')
  
  # streamlit를 통해 이미지를 보여준다.  
  st.image(image1)
  st.divider()
  st.image(image2)
  st.divider()
  st.image(image3)
  st.divider()
  st.image(image4)
  st.divider()
  st.image(image5)
  st.divider()
  st.image(image6)
  st.divider()
  st.image(image7)
  st.divider()
  st.image(image8)
  st.divider()
  st.image(image9)
  st.divider()
  st.image(image10)
  st.divider()
  st.image(image11)
  st.divider()
  st.image(image12)
  st.divider()
  st.image(image13)
  st.divider()
  st.image(image14)
  st.divider()
  st.image(image15)
  st.divider()
  st.image(image16)
  st.divider()
  st.image(image17)
  st.divider()
  st.image(image18)
  st.divider()
  st.image(image19)
  st.divider()
  st.image(image20)
  st.divider()
  st.image(image21)
  st.divider()
  st.image(image22)
  st.divider()
  st.image(image23)
  st.divider()
  st.image(image24)
  st.divider()
  st.image(image25)
  st.divider()
  st.image(image26)
  st.divider()
  st.image(image27)
  st.divider()
  st.image(image28)
  st.divider()
  st.image(image29)
  st.divider()
  st.image(image30)
  st.divider()
  st.image(image31)
  st.divider()
  st.write("by gKim")
  
