import streamlit as st
from PIL import Image # 위에서 선언 후 사용해야한다.

st.title("GAO reports Word Cloud since 2022")

tabs = st.tabs(["GAO_EN", "GAO_한글"])

with tabs[0]:
  # 경로에 있는 이미지 파일을 통해 변수 저장
  img1 = Image.open('images/en/Agriculture and Food.png')
  img2 = Image.open('images/en/Auditing and Financial Management.png')
  img3 = Image.open('images/en/Budget and Spending.png')
  img4 = Image.open('images/en/Business Regulation and Consumer Protection.png')
  img5 = Image.open('images/en/Economic Development.png')
  img6 = Image.open('images/en/Education.png')
  img7 = Image.open('images/en/Employment.png')
  img8 = Image.open('images/en/Energy.png')
  img9 = Image.open('images/en/Equal Opportunity.png')
  img10 = Image.open('images/en/Financial Markets and Institutions.png')
  img11 = Image.open('images/en/GAO Mission and Operations.png')
  img12 = Image.open('images/en/Government Operations.png')
  img13 = Image.open('images/en/Health Care.png')
  img14 = Image.open('images/en/Homeland Security.png')
  img15 = Image.open('images/en/Housing.png')
  img16 = Image.open('images/en/Human Capital.png')
  img17 = Image.open('images/en/Information Management.png')
  img18 = Image.open('images/en/Information Security.png')
  img19 = Image.open('images/en/Information Technology.png')
  img20 = Image.open('images/en/International Affairs.png')
  img21 = Image.open('images/en/Justice and Law Enforcement.png')
  img22 = Image.open('images/en/National Defense.png')
  img23 = Image.open('images/en/Natural Resources and Environment.png')
  img24 = Image.open('images/en/Retirement Security.png')
  img25 = Image.open('images/en/Science and Technology.png')
  img26 = Image.open('images/en/Space.png')
  img27 = Image.open('images/en/Tax Policy and Administration.png')
  img28 = Image.open('images/en/Telecommunications.png')
  img29 = Image.open('images/en/Transportation.png')
  img30 = Image.open('images/en/Veterans.png')
  img31 = Image.open('images/en/Worker and Family Assistance.png')
  img32 = Image.open('images/en/nan.png') 
  
    
  # streamlit를 통해 이미지를 보여준다.
  st.image(img1)
  st.divider()
  st.image(img2)
  st.divider()
  st.image(img3)
  st.divider()
  st.image(img4)
  st.divider()
  st.image(img5)
  st.divider()
  st.image(img6)
  st.divider()
  st.image(img7)
  st.divider()
  st.image(img8)
  st.divider()
  st.image(img9)
  st.divider()
  st.image(img10)
  st.divider()
  st.image(img11)
  st.divider()
  st.image(img12)
  st.divider()
  st.image(img13)
  st.divider()
  st.image(img14)
  st.divider()
  st.image(img15)
  st.divider()
  st.image(img16)
  st.divider()
  st.image(img17)
  st.divider()
  st.image(img18)
  st.divider()
  st.image(img19)
  st.divider()
  st.image(img20)
  st.divider()
  st.image(img21)
  st.divider()
  st.image(img22)
  st.divider()
  st.image(img23)
  st.divider()
  st.image(img24)
  st.divider()
  st.image(img25)
  st.divider()
  st.image(img26)
  st.divider()
  st.image(img27)
  st.divider()
  st.image(img28)
  st.divider()
  st.image(img29)
  st.divider()
  st.image(img30)
  st.divider()
  st.image(img31)
  st.divider()
  st.image(img32)
  st.divider()
  st.text(by gkim)

with tabs[1]:
  # main()
  img = Image.open('images/en/Budget and Spending.png')
  
  # 경로에 있는 이미지 파일을 통해 변수 저장
  
  st.image(img)
  # streamlit를 통해 이미지를 보여준다.
